### PR TITLE
Some changes

### PR DESCRIPTION
**Pull request by khaledhosny**
I’m experimenting with building luaharfbuzz into LuaTeX, here is some of the changes I made.

### CODE REVIEW

**Comment by deepakjois** [comment]
I believe you have commit rights to this repo. So feel free to push this to master. I am a bit busy nowadays, but I might be able to find some time to do a release to LuaRocks, just to keep things consistent.

**Comment by khaledhosny** [comment]
OK, I wanted another eyeball. I’m also still changing stuff as I go with my experiment, so will keep this open until things settle down and then merge.

**Comment by deepakjois** [comment]
I will look through the code later this week, and leave comments if I have any.

**Comment by deepakjois** [comment]
A couple of things:

* If you are changing the names of public fields, (like the `Drop redundant…` commits), do update the luadoc file: https://github.com/ufyTeX/luaharfbuzz/blob/master/src/harfbuzz.luadoc

* I haven’t been following Harfbuzz development very closely, but it seems there is a 2.0 version out. Moreover, with the kind of changes you are making it would make sense to bump the major version. So, if/when I release, I would tag the release as luaharfbuzz 2.0. Makes sense?

**Comment by khaledhosny** [comment]
* I did update the luadoc file for any name change (I also added aliases to the Lua file to not break any existing code).
* Version 2.0 sounds good.

I’m still working on that though,  I keep adding stuff as I continue exploring the integration with LuaTeX, so I’d hold on on merging and releasing for now since things are still evolving. Once the dust settles and may LuaTeX integration is working and more thoroughly tested, I might go more systematic and try to map all HarfBuzz API (at least what makes sense for the Lua module) and then version 2.0 would even be more appropriate.

**Comment by deepakjois** [comment]
Ok sure. I won’t do anything until you commit to master.

**Comment by khaledhosny** [comment]
I think this PR is stable enough and can be merged if you don’t have any objections. I’ll work on another PR that adds more API in a systemic way (right now I was only adding stuff I have immediate need for).

**Comment by deepakjois** [comment]
Go for it!

I will try and find some time to do a release eventually, hopefully by the end of the year.

**Pull request merged**
