### PR TITLE
Add bindings for variable fonts

### LINKED ISSUE #50: Add bindings for variable fonts

### PR DESCRIPTION
**Pull request by zauguin**
Closes #50.

### CODE REVIEW

**Comment by deepakjois** [comment]
I believe you have permissions to commit this to the repo, @zauguin.

I took a quick look, and it looks fine to me.

**Review by deepakjois — APPROVED** [review]

**Comment by zauguin** [comment]
> I believe you have permissions to commit this to the repo, @zauguin.

I do not have any special permissions in this repo.

**Comment by deepakjois** [comment]
I just checked, and you should have contributor access to the repo. I added you a while ago, because I wasn't sure how much time I would have to maintain this repo and I did not want changes to be held up.

image

I will merge the request this time, but you can always push to this repo anytime. I would appreciate it if you created a pull request first though, since that would give me a chance to track changes being made. You don't necessarily have to wait for my approval if I am not able to respond in time.

**Comment by zauguin** [comment]
> I just checked, and you should have contributor access to the repo.

In GitHub "contributor" only means that some commits from me are part of the repository. It is independent from being a ["collaborator" who has push access](https://github.com/ufyTeX/luaharfbuzz/settings/access). I tested it and get

image
when trying to push.

> I will merge the request this time
Thanks.

> I would appreciate it if you created a pull request first though, since that would give me a chance to track changes being made.

Sure, I'll do so.

**Comment by deepakjois** [comment]
I was mistaken. For some reason, I thought I had already added you. 

I just added you to the repo with write access. Please let me know if you still can't push to this repo.

**Comment by zauguin** [comment]
Thanks, it works now :)

**Pull request merged**
